# NOTE: Please validate this file after editing it using
#       Travis WebLint https://lint.travis-ci.org/
#       or travis-lint https://github.com/travis-ci/travis-lint

language: cpp
compiler:
  - gcc
os:
  - linux
sudo: false
cache:
  apt: true

env:
  global:
      # Boost version to use:
      # _MIN is used when building the master branch
      # _MAX is used when building any other branch
    - BOOST_VERSION_MIN="1.49.0"
    - BOOST_VERSION_MAX="1.61.0"
      # List of required boost libraries to build
    - BOOST_LIBS="date_time,filesystem,iostreams,python,regex,system,test"
      # Encrypted COVERITY_SCAN_TOKEN
    - secure: "mYNxD1B8WNSvUeKzInehZ7syi2g1jH2ymeSQxoeKKD2duq3pvNWPdZdc4o9MlWQcAqcz58rhFZRIpuEWCnP0LbbJaG+MyuemMn9uAmg9Y4gFpMsBPHuTdf8pO3rDex+tkrr9puEJFgL+QV/TehxO6NDDpx7UdYvJb+4aZD/auYI="

addons:
  coverity_scan:
    project:
      name: "ledger/ledger"
      description: "Build submitted via Travis CI"
    build_command_prepend: "cmake . -DUSE_PYTHON=ON -DBUILD_DEBUG=ON -DCLANG_GCOV=ON"
    build_command: "make"
    branch_pattern: coverity
  apt:
    sources:
      #- boost-latest
    packages:
      - libgmp-dev
      - libmpfr-dev
      - libedit-dev
      #- libboost1.55-dev
      #- libboost-test1.55-dev
      #- libboost-regex1.55-dev
      #- libboost-python1.55-dev
      #- libboost-system1.55-dev
      #- libboost-date-time1.55-dev
      #- libboost-iostreams1.55-dev
      #- libboost-filesystem1.55-dev
      #- libboost-serialization1.55-dev

before_install:
  # - if [ "${TRAVIS_BRANCH}" = "master" ]; then export BOOST_VERSION="${BOOST_VERSION_MIN}"; else export BOOST_VERSION="${BOOST_VERSION_MAX}"; fi
  - export BOOST_VERSION="${BOOST_VERSION_MAX}"
  - if [ -n "${BOOST_VERSION}" ]; then export BOOST_ROOT="${TRAVIS_BUILD_DIR}/../boost-trunk"; export CMAKE_MODULE_PATH="${BOOST_ROOT}"; fi
  - tools/travis-before_install.sh

install:
  - tools/travis-install.sh

before_script:
  - cmake . -DUSE_PYTHON=ON -DBUILD_DEBUG=ON
  - make

script:
  - ctest --output-on-failure
  - PYTHONPATH=. python python/demo.py

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels: [ "chat.freenode.net#ledger" ]
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0050d91909a8cde39e35
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

