# Since the Travis CI environment http://docs.travis-ci.com/user/ci-environment/
# provides GNU GCC 4.6, which does not support -std=c++11 GNU GCC 4.8 is installed

# NOTE: Please validate this file after editing it using
#       Travis WebLint https://lint.travis-ci.org/
#       or travis-lint https://github.com/travis-ci/travis-lint

language: cpp
compiler:
  - clang
  - gcc
sudo: false
cache:
  apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-4.8
      - g++-4.8
      - libgmp-dev
      - libmpfr-dev
      - libedit-dev
      - libboost1.55-dev
      - libboost-test1.55-dev
      - libboost-regex1.55-dev
      - libboost-python1.55-dev
      - libboost-system1.55-dev
      - libboost-date-time1.55-dev
      - libboost-iostreams1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-serialization1.55-dev

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - cmake . -DUSE_PYTHON=ON
  - make

script:
  - make test
  - PYTHONPATH=. python python/demo.py

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels: [ "chat.freenode.net#ledger" ]
    on_success: change
    on_failure: change
